"""Initial migration with expanded models

Revision ID: c10494b2f023
Revises: 
Create Date: 2026-06-24 19:43:02.858471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c10494b2f023'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rtsp_url', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('zone_config', sa.Text(), nullable=True),
    sa.Column('stream_config', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cloud_sync_queue',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('queued_at', sa.DateTime(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloud_sync_queue_record_id'), 'cloud_sync_queue', ['record_id'], unique=False)
    op.create_index(op.f('ix_cloud_sync_queue_status'), 'cloud_sync_queue', ['status'], unique=False)
    op.create_index(op.f('ix_cloud_sync_queue_table_name'), 'cloud_sync_queue', ['table_name'], unique=False)
    op.create_table('daily_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('camera_id', sa.String(length=36), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_entries', sa.Integer(), nullable=False),
    sa.Column('total_exits', sa.Integer(), nullable=False),
    sa.Column('unique_visitors', sa.Integer(), nullable=False),
    sa.Column('avg_dwell_seconds', sa.Float(), nullable=False),
    sa.Column('peak_hour', sa.Integer(), nullable=True),
    sa.Column('peak_count', sa.Integer(), nullable=False),
    sa.Column('conversion_rate', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_reports_date'), 'daily_reports', ['date'], unique=False)
    op.create_table('heatmap_cells',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('camera_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('cell_x', sa.Integer(), nullable=False),
    sa.Column('cell_y', sa.Integer(), nullable=False),
    sa.Column('density', sa.Float(), nullable=False),
    sa.Column('visit_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heatmap_cells_camera_id'), 'heatmap_cells', ['camera_id'], unique=False)
    op.create_index(op.f('ix_heatmap_cells_date'), 'heatmap_cells', ['date'], unique=False)
    op.create_table('hourly_counts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('camera_id', sa.String(length=36), nullable=False),
    sa.Column('hour', sa.DateTime(), nullable=False),
    sa.Column('entries', sa.Integer(), nullable=False),
    sa.Column('exits', sa.Integer(), nullable=False),
    sa.Column('peak_count', sa.Integer(), nullable=False),
    sa.Column('total_tracks', sa.Integer(), nullable=False),
    sa.Column('avg_dwell_seconds', sa.Float(), nullable=False),
    sa.Column('max_dwell_seconds', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hourly_counts_camera_id'), 'hourly_counts', ['camera_id'], unique=False)
    op.create_index(op.f('ix_hourly_counts_hour'), 'hourly_counts', ['hour'], unique=False)
    op.create_table('person_tracks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('camera_id', sa.String(length=36), nullable=False),
    sa.Column('session_track_id', sa.Integer(), nullable=False),
    sa.Column('entry_time', sa.DateTime(), nullable=False),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('dwell_seconds', sa.Float(), nullable=True),
    sa.Column('zones_visited', sa.Text(), nullable=True),
    sa.Column('path_json', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_tracks_camera_id'), 'person_tracks', ['camera_id'], unique=False)
    op.create_index(op.f('ix_person_tracks_date'), 'person_tracks', ['date'], unique=False)
    op.create_index(op.f('ix_person_tracks_entry_time'), 'person_tracks', ['entry_time'], unique=False)
    op.create_table('queue_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('camera_id', sa.String(length=36), nullable=False),
    sa.Column('zone_name', sa.String(length=128), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('queue_depth', sa.Integer(), nullable=False),
    sa.Column('avg_wait_seconds', sa.Float(), nullable=True),
    sa.Column('max_wait_seconds', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queue_snapshots_camera_id'), 'queue_snapshots', ['camera_id'], unique=False)
    op.create_index(op.f('ix_queue_snapshots_timestamp'), 'queue_snapshots', ['timestamp'], unique=False)
    op.create_table('stores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_timestamp'), 'transactions', ['timestamp'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('zone_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('track_id', sa.String(length=36), nullable=False),
    sa.Column('camera_id', sa.String(length=36), nullable=False),
    sa.Column('zone_name', sa.String(length=128), nullable=False),
    sa.Column('zone_type', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zone_events_camera_id'), 'zone_events', ['camera_id'], unique=False)
    op.create_index(op.f('ix_zone_events_timestamp'), 'zone_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_zone_events_track_id'), 'zone_events', ['track_id'], unique=False)
    op.create_table('transaction_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('track_id', sa.String(length=36), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_events')
    op.drop_index(op.f('ix_zone_events_track_id'), table_name='zone_events')
    op.drop_index(op.f('ix_zone_events_timestamp'), table_name='zone_events')
    op.drop_index(op.f('ix_zone_events_camera_id'), table_name='zone_events')
    op.drop_table('zone_events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_transactions_timestamp'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('stores')
    op.drop_index(op.f('ix_queue_snapshots_timestamp'), table_name='queue_snapshots')
    op.drop_index(op.f('ix_queue_snapshots_camera_id'), table_name='queue_snapshots')
    op.drop_table('queue_snapshots')
    op.drop_index(op.f('ix_person_tracks_entry_time'), table_name='person_tracks')
    op.drop_index(op.f('ix_person_tracks_date'), table_name='person_tracks')
    op.drop_index(op.f('ix_person_tracks_camera_id'), table_name='person_tracks')
    op.drop_table('person_tracks')
    op.drop_index(op.f('ix_hourly_counts_hour'), table_name='hourly_counts')
    op.drop_index(op.f('ix_hourly_counts_camera_id'), table_name='hourly_counts')
    op.drop_table('hourly_counts')
    op.drop_index(op.f('ix_heatmap_cells_date'), table_name='heatmap_cells')
    op.drop_index(op.f('ix_heatmap_cells_camera_id'), table_name='heatmap_cells')
    op.drop_table('heatmap_cells')
    op.drop_index(op.f('ix_daily_reports_date'), table_name='daily_reports')
    op.drop_table('daily_reports')
    op.drop_index(op.f('ix_cloud_sync_queue_table_name'), table_name='cloud_sync_queue')
    op.drop_index(op.f('ix_cloud_sync_queue_status'), table_name='cloud_sync_queue')
    op.drop_index(op.f('ix_cloud_sync_queue_record_id'), table_name='cloud_sync_queue')
    op.drop_table('cloud_sync_queue')
    op.drop_table('cameras')
    # ### end Alembic commands ###
